### ISSUE TITLE
testing in CI, how to run an X11 server?

### ISSUE THREAD

**Issue by Place1** [Place1/react-native-gtk#1]
I'm trying to figure out how to test both the c++ bindings and the resulting node usage of them for `gtk-node`. CircleCI currently is failing on the tests because there's no x11 server available for GTK.

**Comment by clayrisser** [comment]
I recommend we use Drone for our CI. It's open source so we can run it on our own servers. We can use my drone setup for now. The reason we should use drone is that every step runs inside its own Docker container. It is possible to setup an x11 server inside of a docker container. I've done it before.

**Comment by clayrisser** [comment]
Did you solve this?

**Comment by Place1** [comment]
yep, just using `xvfb` for a headless x11 server.

relevant line is: https://github.com/Place1/react-native-gtk/blob/3e59f8f882108511cc02c2921ece62e05317f6c8/.circleci/config.yml#L15

**Comment by clayrisser** [comment]
Nice
