### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#10]
We should nail out a project roadmap in the near future

**Comment by Place1** [comment]
I agree. Things on my mind are:
- research gjs and seed's GI bindings
- ask around for feedback on the current approach vs. GI
- figureout packaging for `react-native-gtk` applications (how will application devs create installable apps?) Perhaps we should make a react-native-gtk cli?
- react-native-gtk's implementation of flexbox layout. currently there's just a `setInterval` that runs the layout :P
- testing react-native-gtk and gtk-node!!! this is very important!

**Comment by Place1** [comment]
Update: so gobject introspection is a far better solution to the custom bindings that were being written in the gtk-node package. As a result we’re going to make use of my fork of node-gir here: https://github.com/Place1/node-gir

It’s not ready just yet to be used here in react-native-gtk so for the time being this project will have to wait, but hopefully not for long as the ‘signals’ need a bit more work on node-gir. 

Once node-gir is ready, this repo will be converted away from a mono-repo to just house the react-native-gtk package.

**Comment by Place1** [comment]
update:
i've update this repo to use node-gir, published from https://github.com/Place1/node-gir

I'm focusing on node-gir currently to get signals more robust. I'm also working on it's architecture a fair bit to simplify the codebase.

I've added a brief roadmap to the readme on this repository as well.
