### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#11]
We need to create a contribution guide

**Comment by Place1** [comment]
things off the top of my head that we could include in the guide:
- create an issue describing your goal
- open a pull request early so we can provide input/help as you go
- make sure you're changes pass CI and include tests

we can also create an issue template:
- we should make sure issues are tagged with `gtk-node` or `react-native-gtk` so we know which package they're for.

**Comment by clayrisser** [comment]
Speaking of tests, is code coverage implemented?

**Comment by Place1** [comment]
Jest could give us coverage for react-native-gtk. I’m not sure how useful
jest’s coverage for gtk-node would be (as it’s just using bindings). I’ve
experimented with some c++ unittesting frameworks but struggled with the
compiler a bit, setting up some c++ unit tests would have to be done before
coverage for gtk-node

**Comment by clayrisser** [comment]
We should reopen this because that's only a tiny piece of the contribution guide. Most developers know how to fork a repo. What they don't know is where they fit in the project, and how to get started. They need to know the rules of the game.

**Comment by Place1** [comment]
Fair enough.
