### ISSUE TITLE
gtk-node eslint

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#12]
We should probably lint the javascript files in gtk-node. Probably our linting rules should follow a similar convention to our tslint rules. Also, we might want to implement a well-supported linting configuration, like the airbnb linting rules. I'm not sure exactly how this will stack up against our tslint rules, especially with react thrown in the mix.

**Comment by Place1** [comment]
Yep i'll setup tslint for the `gtk-node` package. The only js file in that package is the `index.js` file which should not be changed much over time, so it's probably not worth adding a full eslint setup for a single file. Given there will be some tests written in TypeScript it makes sense to add tslint in gtk-node as well.

**Comment by clayrisser** [comment]
Ok, cool, sounds great
