### ISSUE TITLE
Automated development

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#16]
I wonder if some of the work could be automated using a tool similar to Coccinelle. I know this tool is heavily used in automating the development of the Linux kernel.

http://coccinelle.lip6.fr/ce.php
https://pypi.python.org/pypi/coccigrep

**Comment by harisvsulaiman** [comment]
@jamrizzi Gtk has metadata in the form of Gir, why don't we use that?

**Comment by clayrisser** [comment]
I'm going to close this because gobject introspection is so much better.
