### ISSUE TITLE
Failed at the node-gir@0.1.2

### ISSUE THREAD

**Issue by GordonCode25** [Place1/react-native-gtk#19]
npm install fails. Latest version of node.

Darwin 17.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-gir@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gir@0.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-gir package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by GordonCode25** [comment]
ok, quite clearly that wasn't the latest version of node. Updated and tried again: new error

CXX(target) Release/obj.target/girepository/src/init.o
In file included from ../src/init.cc:5:
../src/util.h:4:10: fatal error: 'glib.h' file not found
#include <glib.h>

**Comment by GordonCode25** [comment]
ok solved.
You have to clone both git repos. Then go into gir and run npm install then into the other and run npm install. Link them at some point. Maybe you need rearrange your install help.

**Comment by Place1** [comment]
Sorry for this. The error you had makes it sound like your system didn't have the glib development libs installed, but your follow up makes it sound like that's not the case?
`npm install react-native-gtk` or `npm install` after cloning should install `node-gir` and build it correctly. I believe the only dependency required is `gobject-introspection`.

**Comment by GordonCode25** [comment]
I got another error after that and gave up, I can try again later if you like.


Your project sounds quite interesting.


________________________________
