### ISSUE TITLE
Panel instead of window?

### ISSUE THREAD

**Issue by nkkollaw** [Place1/react-native-gtk#28]
I would like to attempt creating a panel.

Is there any way to have a panel instead of a window as the container for components?

By panel I mean a dock or topbar--like xfce4-panel, vala-panel, DockbarX, Plank, etc.

**Comment by Place1** [comment]
I wouldn't be sure to be honest. This lib is super experimental right now. If you're keen to dive down the rabbit hole i'd be interested to see if it could work. You'd likely need to use [node-gir](https://github.com/place1/node-gir) to see what native bindings are required for this type of app, once that's figured out you could then see how the react bindings might work
