### ISSUE TITLE
Setter multiple parameters

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#7]
It looks like IMPLEMENT_SETTER only support one parameter
Any ideas only solving it for multiple paramters?
Maybe we could have IMPLEMENT_SETTER_1PARAM, IMPLEMENT_SETTER_2PARAM, IMPLEMENT_SETTER_3PARAM, etc . . .
Unless c++ can auto detect which macro to run based on the number of parameters

**Comment by clayrisser** [comment]
https://stackoverflow.com/questions/16683146/can-macros-be-overloaded-by-number-of-arguments

**Comment by Place1** [comment]
what's the gtk setter you've bumped into?

**Comment by clayrisser** [comment]
Nothing specific, I just know it will be an issue at some point. Just thinking ahead.

**Comment by Place1** [comment]
I've already bumped into this for signal callbacks that require a return value, or have multiple arguments. Currently i've just avoided the autobindings for those (see Window onClose for an example) but I'd like to figure out a better way to handle this through macros.

**Comment by Place1** [comment]
no longer relevant given we're using node-gir

**Comment by clayrisser** [comment]
Niiiiice, this was something I was worried about.
