### ISSUE TITLE
GTK library on Windows?

### ISSUE THREAD

**Issue by clayrisser** [Place1/react-native-gtk#8]
What approach should be used to get gtk working on Windows?

I have done this before with gtk python.

Convention has the gtk library at `C:/gtk`

Possibly we could create our own gtk installer

**Comment by Place1** [comment]
Closing as this issue now belongs on https://github.com/Place1/node-gir

**Comment by clayrisser** [comment]
So, we're not using lerna.

**Comment by Place1** [comment]
No. Lerna was only useful when we wanted to develop multiple packages in
the same got repo.
